name: 'Terraform validate, plan and apply'
description: 'Terraform validate, plan and apply'

inputs:
  directory:
    description: 'Terraform directory'
    required: true
  apply:
    description: 'Apply Terraform plan'
    required: false
    default: 'false'
  plan-comment:
    description: 'Post PR comment with Terraform plan'
    required: false
    default: 'true'
  image-tag:
    description: 'Docker image tag'
    required: true
  telegram-bot-token:
    description: 'Telegram bot token'
    required: true
  google-credentials-json:
    description: 'Google credentials JSON'
    required: true
  google-spreadsheet-id:
    description: 'Google spreadsheet ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.5

    - name: Init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Format check
      run: terraform fmt -check
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Validate
      run: terraform validate
      shell: bash
      working-directory: ${{ inputs.directory }}

    - uses: terraform-linters/setup-tflint@v6
      name: Setup TFLint
      with:
        tflint_version: v0.60.0
        cache: true

    - name: Init TFLint
      run: tflint --init
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact
      shell: bash

    - name: Plan
      id: plan
      run: |
        cat > terraform.tfvars.json <<EOF
        {
          "telegram_bot_token": "${{ inputs.telegram-bot-token }}",
          "google_credentials_json": $(echo '${{ inputs.google-credentials-json }}' | jq -Rs .),
          "google_spreadsheet_id": "${{ inputs.google-spreadsheet-id }}",
          "image_tag": "${{ inputs.image-tag }}"
        }
        EOF
        terraform plan -out=tfplan
      shell: bash
      working-directory: ${{ inputs.directory }}
      continue-on-error: ${{ inputs.plan-comment == 'true' }}

    - name: Post PR comment
      if: inputs.plan-comment == 'true'
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: tfplan
        working-directory: ${{ inputs.directory }}
        skip-empty: true

    - name: Apply
      if: inputs.apply == 'true'
      run: terraform apply tfplan
      shell: bash
      working-directory: ${{ inputs.directory }}
