name: 'Terraform validate and plan and apply'
description: 'Terraform validate and plan and apply'

inputs:
  directory:
    description: 'Terraform directory'
    required: true
  apply:
    description: 'Apply Terraform plan'
    required: false
    default: 'false'
  plan-comment:
    description: 'Post PR comment with Terraform plan'
    required: false
    default: 'true'
  telegram-bot-token:
    description: 'Telegram bot token'
    required: true
  google-credentials-json:
    description: 'Google credentials JSON'
    required: true
  google-spreadsheet-id:
    description: 'Google spreadsheet ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: '0.9.7'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Format check
      run: terraform fmt -check
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Validate
      run: terraform validate
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Plan
      id: plan
      run: |
        cat > terraform.tfvars.json <<EOF
        {
          "telegram_bot_token": "${{ inputs.telegram-bot-token }}",
          "google_credentials_json": $(echo '${{ inputs.google-credentials-json }}' | jq -Rs .),
          "google_spreadsheet_id": "${{ inputs.google-spreadsheet-id }}"
        }
        EOF
        terraform plan -out=tfplan
      shell: bash
      working-directory: ${{ inputs.directory }}
      continue-on-error: ${{ inputs.plan-comment == 'true' }}

    - name: Post PR comment
      if: inputs.plan-comment == 'true'
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: tfplan
        working-directory: ${{ inputs.directory }}
        skip-empty: true

    - name: Apply
      if: inputs.apply == 'true'
      run: terraform apply tfplan
      shell: bash
      working-directory: ${{ inputs.directory }}
