name: 'Check'
description: 'Run checks'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true

    - name: Test
      shell: bash
      run: make test

    - name: Vet
      shell: bash
      run: make vet

    - name: Check formatting
      shell: bash
      run: make fmtcheck

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.10.1
